name: indirla
services:
- name: web
  source_dir: /
  github:
    repo: your-username/indirla
    branch: main
  run_command: npm start
  build_command: |
    apt-get update && 
    apt-get install -y python3 python3-pip ffmpeg && 
    pip3 install yt-dlp && 
    npm install && 
    npm run build
  environment_slug: ubuntu-22-04
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  env:
  - key: NODE_ENV
    value: production
  - key: PATH
    value: $PATH:/usr/local/bin